port: PORT
managementApiSecret: SECRET
databases:
  default:
    migrations: true
    connector: postgres
    host: DATABASE_HOST
    port: DATABASE_PORT
    user: DATABASE_USER
    password: DATABASE_PASSWORD
